# -*- coding: utf-8 -*-
"""Asignación_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kf1bU3EBdV9I7SgOZrAlBrR7lLmv6QuR

#Codigo funcional de funciones

$$y1=log(x)$$

##Condiciones

1. $x>0$
"""

from math import log

x = float(input('Asigne un valor a x: '))
if (x>0):
  y1=log(x,10)
  print('y1 es {:.3f}'.format(y1))
else:
  print('fuera del dominio ')

"""$$y2=log(\sqrt{x})$$"""

from math import log
from math import sqrt 

x = float(input('Asigne un valor a x: '))
if (x>0):
  y2=log(sqrt(x),10)
  print('y2 es {:.2f}'.format(y2))
else:
  print('fuera del dominio')

"""$$y3=log(\sqrt{x^{2}-1})$$"""

from math import log
from math import sqrt 

x = float(input('Asigne un valor a x: '))
if (x!=1) and (x!=0):
  y3=log(sqrt((x**2)-1),10)
  print('y3 es {:.2}'.format(y3))
else:
  print('fuera del dominio')

"""$$y4=\frac{log\sqrt{x-1}}{x^{2}+1}$$"""

from math import log
from math import sqrt 
from decimal import Decimal

x = float(input('Asigne un valor a x: '))
if (x>1):
  y4=Decimal(log(sqrt(x-1),10)) / Decimal((x**2)+1)
  print('y4 es {:.2}'.format(y4))
else:
  print('Fuera del dominio')

"""$$y5=\frac{x-1}{log(x)}$$"""

from math import log
from decimal import Decimal

x = float(input('Asigne un valor a x: '))
if (x>1):
  y5=Decimal(x-1) / Decimal(log(x,10))
  print('y5 es {:.2f}'.format(y5))
else:
  print('fuera del dominio')

"""$$y6=\frac{1}{x}+\sqrt{x-1}$$"""

from decimal import Decimal
from math import sqrt 

x = float(input('Asigne un valor a x:'))
if (x>=1):
  y6=Decimal(1) / Decimal(x) + sqrt(x-1)
  print('y6 es {:.2f}'.format(y6))
else:
  print('fuera del dominio')

"""$$y7=\frac{1}{x}+\sqrt{x-1}-\frac{1}{log(\frac{1}{x+1})}$$"""



"""$$y8=\frac{2}{x^{2}+1}$$"""



"""$$y9=\frac{1}{n}\sum_{i=1}^{n}{x}_i$$"""



"""$$y10=\frac{1}{n-1}\sum_{i=1}^{n}({x}_i-\bar{x})$$"""



"""$$y11=\frac{\sqrt{y10}}{y9}$$"""

